
/*
 * This stub is generated by jrpc, DO NOT modify it!
 */

#ifndef RPCPP_ECHOCLIENTSTUB_H
#define RPCPP_ECHOCLIENTSTUB_H

#include <jsoncpp/json/json.h>
#include <string>
#include <iostream>
#include "rpcpp/common/noncopyable.h"
#include "rpcpp/client/RpcClient.h"

namespace rpcpp
{

    class echoClientStub : noncopyable
    {
    public:
        echoClientStub(IClientConnector &connector) : client(connector){}
        ~echoClientStub() = default;
        
        std::string echo(std::string message)
        {
            Json::Value params,result;
            params["message"]=message;
            std::cout<<message<<std::endl;
            client.CallMethod("echo",params,result);
            return result["ret"].asString();
        }
        
        
    private:
        RpcClient client;
    };

}
#endif //RPCPP_ECHOCLIENTSTUB_H
